
spring:
  datasource:
    batch:
      url: jdbc:mysql://localhost:3306/order_batch_db
      username: root
      password: CoffeeMaster
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: true
  profiles:
    include:
      - data
logging:
  level:
    org.springframework.batch: DEBUG
