
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service_db
    username: root
    password: CoffeeMaster
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: true
